package org.headb;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MiniSandApplet.java
 *
 * Created on Mar 17, 2009, 1:12:59 PM
 */

/**
 *
 * @author headb
 */
public class MiniSandApplet extends javax.swing.JApplet {

    /** Initializes the applet MiniSandApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sandpilePanel1 = new SandpilePanel();

        sandpilePanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        org.jdesktop.layout.GroupLayout sandpilePanel1Layout = new org.jdesktop.layout.GroupLayout(sandpilePanel1);
        sandpilePanel1.setLayout(sandpilePanel1Layout);
        sandpilePanel1Layout.setHorizontalGroup(
            sandpilePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 521, Short.MAX_VALUE)
        );
        sandpilePanel1Layout.setVerticalGroup(
            sandpilePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 447, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sandpilePanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sandpilePanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SandpilePanel sandpilePanel1;
    // End of variables declaration//GEN-END:variables

}
